version: "3"
services:
  app:
    env_file:
      - .env
    container_name: hrisdexagroup
    restart: always
    build: .
    ports:
      - "$PORT:$PORT"
    links:
      - postgres
      - mongodb
      - rabbitmq
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    env_file:
      - .env
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    env_file:
      - .env

volumes:
  postgres:
    driver: local
  mongo:
    driver: local
  rabbitmq:
    driver: local
